services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:VA7b+kOxGPPheIsUl1ZvzHATkGA7fstaglNe/lkfkrc=
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pvm
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: pvmdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pvm
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
